name: Workload Identity Pool with Github Actions and Terraform

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  TF_VAR_PROJECT_ID: ${{ vars.TF_VAR_PROJECT_ID }}
  TF_VAR_TF_LOG: ${{ vars.TF_VAR_TF_LOG }}
  BACKEND_BUCKET: ${{ vars.BACKEND_BUCKET }}

permissions:
  id-token: write 
  contents: read

jobs:
  stage_resources:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
            workload_identity_provider: 'projects/${{ vars.WORKLOAD_IDENTITY_POOL_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.WORKLOAD_IDENTITY_POOL }}/providers/${{ vars.WORKLOAD_IDENTITY_PROVIDER }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=$BACKEND_BUCKET"

      - name: Terraform Validate
        run: terraform validate        

      - name: Create Terraform Plan
        run: terraform plan -out=mainplan.tfplan
        id: plan    

      - name: Convert Terraform Plan to JSON
        id: convert
        run: terraform show -no-color -json mainplan.tfplan > mainplan.json

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve mainplan.tfplan